<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getApiUsageProjectSummary, type ApiUsageProjectGroup } from '../../../api/admin'

const groups = ref<ApiUsageProjectGroup[]>([])
const contributors = ref<any[]>([])
const UNAVAILABLE_DISPLAY = '—'
const googleUsdIdrRate = Number(import.meta.env.VITE_GOOGLE_COST_USD_IDR_RATE || 0)
const error = ref('')
const provider = ref('')
const operation = ref('')
const query = ref('')
const period = ref('THIS_MONTH')
const range = computed(() => {
  const now = new Date(); const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const iso = (d: Date) => d.toISOString().slice(0, 10)
  if (period.value === 'LAST_30_DAYS') return { dateFrom: iso(new Date(today.getTime() - 29 * 86400000)), dateTo: iso(new Date(today.getTime() + 86400000)) }
  if (period.value === 'LAST_MONTH') return { dateFrom: iso(new Date(now.getFullYear(), now.getMonth() - 1, 1)), dateTo: iso(new Date(now.getFullYear(), now.getMonth(), 1)) }
  return { dateFrom: iso(new Date(now.getFullYear(), now.getMonth(), 1)), dateTo: iso(new Date(now.getFullYear(), now.getMonth() + 1, 1)) }
})
const params = () => Object.fromEntries(Object.entries({ provider: provider.value, operation: operation.value, q: query.value, ...range.value }).filter(([, v]) => v))
const load = async () => { error.value = ''; try { const result = await getApiUsageProjectSummary(params()); groups.value = result?.groups || []; contributors.value = result?.contributors || [] } catch { groups.value = []; contributors.value = []; error.value = 'Monitoring API tidak dapat dimuat.' } }
const providerEvents = computed(() => groups.value.filter((g) => g.provider === 'GOOGLE_MAPS').reduce((sum, g) => sum + (g.requests || 0), 0))
const openAIRequests = computed(() => groups.value.filter((g) => g.provider === 'OPENAI').reduce((sum, g) => sum + (g.requests || 0), 0))
const openAITokens = computed(() => groups.value.filter((g) => g.provider === 'OPENAI').reduce((sum, g) => sum + (g.totalTokens || 0), 0))
const googleCostMicros = computed(() => groups.value.filter((g) => g.provider === 'GOOGLE_MAPS' && g.costState === 'VERIFIED_ESTIMATE').reduce((sum, g) => sum + (g.estimatedPayableCostMicros || 0), 0))
const formatGoogleIdr = (micros: number) => micros === 0 ? 'Rp0' : googleUsdIdrRate > 0 ? `Rp${Math.round(micros / 1e6 * googleUsdIdrRate).toLocaleString('id-ID')}` : 'Kurs IDR belum dikonfigurasi'
const googleCostLabel = computed(() => formatGoogleIdr(googleCostMicros.value))
const openAICostMicros = computed(() => groups.value.filter((g) => g.provider === 'OPENAI' && g.costState === 'VERIFIED_ESTIMATE').reduce((sum, g) => sum + ((g.estimatedCostMicros || 0)), 0))
const openAICostLabel = computed(() => groups.value.some((g) => g.provider === 'OPENAI' && g.costState === 'VERIFIED_ESTIMATE') ? `$${(openAICostMicros.value / 1e6).toFixed(4)}` : 'Belum dikonfigurasi')
const costLabel = (row: ApiUsageProjectGroup) => row.costState === 'BILLING_UNKNOWN' ? 'Belum dapat dipastikan' : row.costState === 'SKU_UNKNOWN' ? 'SKU belum teridentifikasi' : row.costState === 'VERIFIED_ESTIMATE' && row.provider === 'GOOGLE_MAPS' ? formatGoogleIdr(row.estimatedPayableCostMicros || 0) : row.costState === 'VERIFIED_ESTIMATE' ? `$${((row.estimatedPayableCostMicros || row.estimatedCostMicros || 0) / 1e6).toFixed(4)}` : 'Belum dikonfigurasi'
const skuLabel = (row: ApiUsageProjectGroup) => row.costState === 'SKU_UNKNOWN' ? 'Belum teridentifikasi' : row.provider !== 'GOOGLE_MAPS' ? row.skuCategory || row.apiOrModel || '—' : ({ NEARBY_SEARCH: 'Nearby Search Pro', TEXT_SEARCH: 'Text Search Pro', CORE_DETAIL: 'Place Details Pro', BUSINESS_INFO: 'Place Details Enterprise', PLACE_PHOTO: 'Place Details Photos' } as Record<string, string>)[row.skuCategory || row.operation] || row.skuCategory || 'Belum teridentifikasi'
const tokenLabel = (row: { provider: string; totalTokens?: number | null }) => row.provider === 'GOOGLE_MAPS' ? UNAVAILABLE_DISPLAY : row.totalTokens == null ? UNAVAILABLE_DISPLAY : row.totalTokens
const providerLabel = (v: string) => v === 'GOOGLE_MAPS' ? 'Google Maps' : v
onMounted(load)
</script>

<template>
  <section class="monitoring-page compact-admin-page">
    <header class="page-heading"><div><p class="eyebrow">ADMIN MONITORING</p><h1>Monitoring API</h1><p class="muted">Monitoring penggunaan layanan eksternal pada level project. Penggunaan setiap pengguna digabungkan untuk melihat total konsumsi Google Maps dan OpenAI.</p></div></header>
    <div class="filters"><label>Periode<select v-model="period" @change="load"><option value="THIS_MONTH">Bulan Ini</option><option value="LAST_30_DAYS">30 Hari Terakhir</option><option value="LAST_MONTH">Bulan Lalu</option></select></label><label>Provider<select v-model="provider" @change="load"><option value="">Semua Provider</option><option value="GOOGLE_MAPS">Google Maps</option><option value="OPENAI">OpenAI</option></select></label><label>Operasi / SKU / Model<input v-model="query" placeholder="Cari dimensi" @keyup.enter="load" /></label><button type="button" @click="load">Terapkan</button></div>
    <div class="stats"><article><span>Google Maps Provider Events</span><strong>{{ providerEvents }}</strong></article><article><span>OpenAI Requests</span><strong>{{ openAIRequests }}</strong></article><article><span>OpenAI Total Tokens</span><strong>{{ openAITokens }}</strong></article><article><span>Google Maps Cost</span><strong>{{ googleCostLabel }}</strong></article><article><span title="Cost dihitung dari token usage yang dicatat dari response OpenAI dan pricing model yang dikonfigurasi. Tagihan resmi tetap mengikuti OpenAI billing.">OpenAI Cost</span><strong>{{ openAICostLabel }}</strong></article></div>
    <p v-if="error" class="empty">{{ error }}</p>
    <article class="panel"><header><div><h2>Penggunaan Project</h2><p>Free tier dan batas penggunaan provider berlaku pada level project, bukan sebagai kuota terpisah untuk setiap pengguna.</p></div></header><div class="table-wrap"><table><thead><tr><th>Provider</th><th>API / Operasi</th><th>SKU / Model</th><th>Total Request</th><th>Berhasil</th><th>Gagal</th><th>Billable</th><th>Tokens</th><th title="Penggunaan gratis project bulan ini / batas gratis SKU.">Free Usage</th><th>Usage %</th><th>Gross Cost</th><th title="Cost Google Maps ditampilkan dalam Rupiah berdasarkan hasil perhitungan usage internal, pricing Google Maps Platform dalam USD, dan kurs konversi yang dikonfigurasi. Tagihan resmi tetap mengikuti Google Cloud Billing.">Cost</th></tr></thead><tbody><tr v-if="!groups.length"><td colspan="12" class="empty">Belum ada penggunaan provider pada periode ini.</td></tr><tr v-for="row in groups" :key="`${row.provider}-${row.operation}-${row.skuCategory}-${row.apiOrModel}`"><td>{{ providerLabel(row.provider) }}</td><td>{{ row.operation }}</td><td>{{ skuLabel(row) }}</td><td>{{ row.requests || 0 }}</td><td class="usage-success-number">{{ row.success || 0 }}</td><td class="usage-failed-number">{{ row.failed || 0 }}</td><td>{{ row.billableRequests || 0 }}</td><td>{{ tokenLabel(row) }}</td><td>{{ row.costState === 'VERIFIED_ESTIMATE' ? `${(row.freeUsageConsumed || 0).toLocaleString('id-ID')} / ${(row.freeUsageCap || 0).toLocaleString('id-ID')}` : '—' }}</td><td>{{ row.costState === 'VERIFIED_ESTIMATE' && row.freeUsageCap ? `${(((row.freeUsageConsumed || 0) / row.freeUsageCap) * 100).toFixed(1)}%` : '—' }}</td><td>{{ row.costState === 'VERIFIED_ESTIMATE' && row.provider === 'GOOGLE_MAPS' ? formatGoogleIdr(row.grossCostMicros || 0) : '—' }}</td><td>{{ costLabel(row) }}</td></tr></tbody></table></div></article>
    <article class="panel"><header><div><h2>Kontribusi Pengguna</h2><p>Kontribusi dihitung dari provider events pengguna terhadap total project pada dimensi dan periode yang sama.</p></div></header><div class="table-wrap"><table><thead><tr><th>Pengguna</th><th>Provider / Operasi</th><th>Provider Events</th><th>Tokens</th><th>Cost</th><th>Kontribusi Request</th><th>Kontribusi Token</th></tr></thead><tbody><tr v-if="!contributors.length"><td colspan="7" class="empty">Belum ada kontribusi pengguna pada periode ini.</td></tr><tr v-for="row in contributors" :key="`${row.userId}-${row.provider}-${row.operation}-${row.apiOrModel}`"><td><strong>{{ row.userName || row.userId }}</strong><small>{{ row.employeeId || 'Employee ID tidak tersedia' }}</small></td><td>{{ providerLabel(row.provider) }} / {{ row.operation }}</td><td>{{ row.requests || 0 }}</td><td>{{ tokenLabel(row) }}</td><td>{{ row.provider === 'OPENAI' && row.costState === 'VERIFIED_ESTIMATE' ? `$${((row.estimatedCostMicros || 0) / 1e6).toFixed(4)}` : row.provider === 'OPENAI' ? 'Belum dikonfigurasi' : '—' }}</td><td>{{ row.contributionPercent.toFixed(1) }}%</td><td>{{ row.provider === 'OPENAI' && row.tokenContributionPercent != null ? `${row.tokenContributionPercent.toFixed(1)}%` : '—' }}</td></tr></tbody></table></div></article>
  </section>
</template>

<style scoped>
.monitoring-page{display:grid;gap:.9rem;padding:.2rem}.page-heading h1{margin:.15rem 0;font-size:1.35rem}.eyebrow{margin:0;color:#0b7766;font-size:.65rem;font-weight:800;letter-spacing:.1em}.muted,.panel p{margin:0;color:var(--text-muted);font-size:.72rem;line-height:1.5}.filters,.stats{display:grid;gap:.55rem}.filters{grid-template-columns:1fr 1fr 1.5fr auto;padding:.65rem;background:#fff;border:1px solid var(--border-light);border-radius:10px}.filters label{display:grid;gap:.2rem;color:var(--text-muted);font-size:.65rem;font-weight:700}.filters select,.filters input,.filters button{min-height:30px;padding:.3rem .55rem;border:1px solid var(--border-light);border-radius:7px;background:#fff;font-size:.72rem}.filters button{align-self:end;background:var(--brand-blue);color:#fff;font-weight:700;cursor:pointer}.stats{grid-template-columns:repeat(4,1fr)}.stats article,.panel{padding:.85rem;background:#fff;border:1px solid var(--border-light);border-radius:10px}.stats span{display:block;color:var(--text-muted);font-size:.66rem}.stats strong{display:block;margin-top:.25rem;font-size:1.15rem}.panel header{margin-bottom:.55rem}.panel h2{margin:0 0 .2rem;font-size:.85rem}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.7rem}th,td{padding:.5rem .4rem;border-top:1px solid #eef2f6;text-align:left;white-space:nowrap}th{color:var(--text-muted);font-size:.62rem;text-transform:uppercase}td small{display:block;color:var(--text-muted);margin-top:.15rem}.empty{padding:.7rem;color:var(--text-muted);font-size:.75rem}@media(max-width:760px){.filters,.stats{grid-template-columns:1fr 1fr}.filters button{grid-column:1/-1}.stats article:last-child{grid-column:1/-1}}@media(max-width:480px){.filters,.stats{grid-template-columns:1fr}}
</style>
