import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

test('Admin Account Detail renders monitoring labels and honest unknown states', () => {
  const source = fs.readFileSync(new URL('../src/views/Admin/Accounts/AdminAccountDetailView.vue', import.meta.url), 'utf8')
  for (const label of ['Penggunaan API Pengguna', 'Total Request', 'Berhasil', 'Gagal', 'Kontribusi Project', 'Cost', 'Aktivitas', 'Cache', 'Request Provider', 'Status', 'Detail', 'Provider / Operasi', 'SKU / Model', 'Status Provider', 'Status Aplikasi', 'HTTP Provider', 'HTTP Aplikasi', 'Riwayat Penggunaan API', 'Tampilkan 10 Lagi']) {
    assert.match(source, new RegExp(label))
  }
  assert.match(source, /Belum dikonfigurasi/)
  assert.match(source, /provider_hit_count/)
  assert.match(source, /cache_status/)
  for (const label of ['Hari Ini', '24 Jam Terakhir', '7 Hari Terakhir', 'Bulan Ini', 'Custom', 'Tampilkan 10 Lagi', 'Reset Filter']) {
    assert.match(source, new RegExp(label))
  }
  assert.match(source, /providerHistoryVisible = ref\(10\)/)
  assert.match(source, /activityHistoryVisible = ref\(10\)/)
  assert.match(source, /meaningfulActivityHistory/)
  assert.match(source, /FIND_MENU: 'Cari Menu'/)
  assert.match(source, /providerDetailItems/)
  assert.match(source, /activityProviderOperation/)
  assert.match(source, /item\.requestId/)
  assert.match(source, /Total request mencakup request provider yang berhasil maupun gagal/)
  assert.match(source, /Menampilkan aktivitas pengguna yang terkait dengan penggunaan Google Maps atau OpenAI/)
  assert.match(source, /grid-template-columns: 1fr 1fr;\s+gap: 0\.6rem/)
  assert.match(source, /\.usage-card \{ margin-top: \.45rem; display: flex; flex-direction: column; \}/)
  assert.match(source, /usage-detail-panel/)
  assert.match(source, /colspan="7"/)
  assert.match(source, /colspan="6"/)
  assert.match(source, /expandedActivityKey/)
  assert.match(source, /expandedProviderKey/)
  assert.match(source, /consolidatedHistory/)
  assert.match(source, /item.requestId === activity.requestId/)
  assert.match(source, /account-info-columns/)
  assert.match(source, /account-info-stack left-stack/)
  assert.match(source, /account-info-stack right-stack/)
  assert.match(source, /Validasi Sesi/)
  assert.match(source, /Muat Data Customer/)
  assert.match(source, /activityModeOptions/)
  assert.match(source, /normalizeActivityMode/)
  assert.match(source, /activityMode = ref\('user'\)/)
assert.match(source, /detail-toggle/)
assert.match(source, /provider-main-row/)
assert.match(source, /provider-col-provider/)
assert.match(source, /overflow-wrap: normal/)
assert.match(source, /word-break: normal/)
assert.match(source, /Credential Alias/)
  assert.match(source, /Cached Tokens/)
  assert.match(source, /historyStatusOptions/)
  assert.match(source, /Hapus dari tampilan/)
  assert.match(source, /Hapus riwayat dari tampilan\?/)
  assert.match(source, /history-hide-button/)
  assert.match(source, /hidden-history-meta/)
  assert.match(source, /hideApiUsageHistory/)
})

test('project monitoring table keeps cost fields under deterministic headers', () => {
  const source = fs.readFileSync(new URL('../src/views/Admin/ApiUsage/AdminApiUsageView.vue', import.meta.url), 'utf8')
  for (const label of ['Total Request', 'Berhasil', 'Gagal', 'Billable', 'Free Usage', 'Usage %', 'Gross Cost', 'Cost']) assert.match(source, new RegExp(label))
  assert.match(source, /row\.success \|\| 0/)
  assert.match(source, /row\.failed \|\| 0/)
  assert.match(source, /row\.billableRequests \|\| 0/)
  assert.match(source, /row\.freeUsageConsumed.*row\.freeUsageCap/)
  assert.match(source, /row\.grossCostMicros/)
  assert.match(source, /estimatedPayableCostMicros/)
  assert.match(source, /SKU belum teridentifikasi/)
})

test('monitoring token placeholders preserve Google unavailable and OpenAI numeric semantics', () => {
  const source = fs.readFileSync(new URL('../src/views/Admin/ApiUsage/AdminApiUsageView.vue', import.meta.url), 'utf8')
  assert.match(source, /const UNAVAILABLE_DISPLAY = '—'/)
  assert.match(source, /row\.provider === 'GOOGLE_MAPS' \? UNAVAILABLE_DISPLAY/)
  assert.match(source, /row\.totalTokens == null \? UNAVAILABLE_DISPLAY : row\.totalTokens/)
  assert.doesNotMatch(source, /ï¿½|Ã¢â‚¬|â€”/)
  assert.match(source, /Google Maps Cost/)
  assert.match(source, /OpenAI Cost[\s\S]*Belum dikonfigurasi/)
})

test('Google and OpenAI cost displays keep separate currencies', () => {
  const source = fs.readFileSync(new URL('../src/views/Admin/ApiUsage/AdminApiUsageView.vue', import.meta.url), 'utf8')
  assert.match(source, /VITE_GOOGLE_COST_USD_IDR_RATE/)
  assert.match(source, /formatGoogleIdr/)
  assert.match(source, /Google Maps Cost/)
  assert.match(source, /OpenAI Cost/)
  assert.match(source, /Kurs IDR belum dikonfigurasi/)
  assert.match(source, /toFixed\(4\)/)
})
